### ISSUE TITLE
Is any way to change the default black background?

### ISSUE THREAD

**Issue by Gaia-X-Alter** [EYHN/space-thumbnails#10]
Is any way to change the default black background?

**Comment by EYHN** [comment]
This is a bug in Windows 10 that also affects other thumbnails – for example transparent PNG images [here](https://www.reddit.com/r/Windows10/comments/8ah07d/my_every_png_file_thumbnail_background_is_black/) and [here](https://answers.microsoft.com/en-us/windows/forum/all/black-background-on-thumbnails-i-need-it-to-be/d72c57b6-d2ad-415a-9198-ff955a07114d).

**Comment by Gaia-X-Alter** [comment]
> This is a bug in Windows 10 that also affects other thumbnails – for example transparent PNG images [here](https://www.reddit.com/r/Windows10/comments/8ah07d/my_every_png_file_thumbnail_background_is_black/) and [here](https://answers.microsoft.com/en-us/windows/forum/all/black-background-on-thumbnails-i-need-it-to-be/d72c57b6-d2ad-415a-9198-ff955a07114d).

Is it possible to manually give a gray background instead ?
